<?php
// $Id$

/**
 * Implement hook_install().
 */
function overlay_install() {
  // If the edit mode toggle link is in place, add the overlay-exclude class to
  // it so it does not open in the overlay.
  $options = array(
    'attributes' => array(
      'class' => 'overlay-exclude',
    ),
  );

  db_update('menu_links')
    ->condition('menu_name', 'admin_shortcuts')
    ->condition('link_path', 'edit-mode/toggle')
    ->fields(array('options' => serialize($options)))
    ->execute();
}
